version: 2.1

orbs:
  yarn: artsy/yarn@6.1.0
  auto: artsy/auto@2.1.0

workflows:
  build_and_verify:
    jobs:
      - yarn/workflow-queue
      - yarn/update-cache:
          requires:
            - yarn/workflow-queue
      - yarn/type-check:
          requires:
            - yarn/workflow-queue
      - auto/publish:
          context: npm-deploy
          filters:
            branches:
              only:
                - main
          requires:
            - yarn/type-check
            - yarn/update-cache
